<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="m1" nsURI="http://www.example.org/m1" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="Client" instanceClassName="Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="portclient" upperBound="-1"
        eType="#//PortClient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RPC" instanceClassName="Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="Serveur" instanceClassName="Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="System" instanceTypeName="Config">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rpc" upperBound="-1" eType="#//RPC"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serveur" upperBound="-1"
        eType="#//Serveur" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" upperBound="-1"
        eType="#//Client" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortClient"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortClientRequis" eSuperTypes="#//PortClient"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortclientFourni" eSuperTypes="#//PortClient"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleRPC"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleRPCFourni"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlueRPC"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoleRPCRequis"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerConf" instanceClassName="Configuration"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortConf"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortConfFourni"/>
  <eClassifiers xsi:type="ecore:EClass" name="PortConfRequis"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lien"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindingRequis"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binding"/>
  <eClassifiers xsi:type="ecore:EClass" name="BindingFourni"/>
</ecore:EPackage>
